basic.showIcon(IconNames.Snake)
basic.forever(function () {
    cuteBot.forward()
    basic.pause(100)
    cuteBot.motors(100, 20)
    basic.pause(1000)
    cuteBot.forward()
    basic.pause(100)
    cuteBot.forward()
    basic.pause(100)
    cuteBot.motors(20, 100)
    basic.pause(1000)
    cuteBot.forward()
    basic.pause(100)
})
